/* 
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DetailedAthlete {
  /// The unique identifier of the athlete
  #[serde(rename = "id")]
  id: Option<i32>,
  /// Resource state, indicates level of detail. Possible values: 1 -> \"meta\", 2 -> \"summary\", 3 -> \"detail\"
  #[serde(rename = "resource_state")]
  resource_state: Option<i32>,
  /// The athlete's first name.
  #[serde(rename = "firstname")]
  firstname: Option<String>,
  /// The athlete's last name.
  #[serde(rename = "lastname")]
  lastname: Option<String>,
  /// URL to a 62x62 pixel profile picture.
  #[serde(rename = "profile_medium")]
  profile_medium: Option<String>,
  /// URL to a 124x124 pixel profile picture.
  #[serde(rename = "profile")]
  profile: Option<String>,
  /// The athlete's city.
  #[serde(rename = "city")]
  city: Option<String>,
  /// The athlete's state or geographical region.
  #[serde(rename = "state")]
  state: Option<String>,
  /// The athlete's country.
  #[serde(rename = "country")]
  country: Option<String>,
  /// The athlete's sex.
  #[serde(rename = "sex")]
  sex: Option<String>,
  /// Deprecated.  Use summit field instead. Whether the athlete has any Summit subscription.
  #[serde(rename = "premium")]
  premium: Option<bool>,
  /// Whether the athlete has any Summit subscription.
  #[serde(rename = "summit")]
  summit: Option<bool>,
  /// The time at which the athlete was created.
  #[serde(rename = "created_at")]
  created_at: Option<String>,
  /// The time at which the athlete was last updated.
  #[serde(rename = "updated_at")]
  updated_at: Option<String>,
  /// The athlete's follower count.
  #[serde(rename = "follower_count")]
  follower_count: Option<i32>,
  /// The athlete's friend count.
  #[serde(rename = "friend_count")]
  friend_count: Option<i32>,
  /// The athlete's preferred unit system.
  #[serde(rename = "measurement_preference")]
  measurement_preference: Option<String>,
  /// The athlete's FTP (Functional Threshold Power).
  #[serde(rename = "ftp")]
  ftp: Option<i32>,
  /// The athlete's weight.
  #[serde(rename = "weight")]
  weight: Option<f32>,
  /// The athlete's clubs.
  #[serde(rename = "clubs")]
  clubs: Option<Vec<::models::SummaryClub>>,
  /// The athlete's bikes.
  #[serde(rename = "bikes")]
  bikes: Option<Vec<::models::SummaryGear>>,
  /// The athlete's shoes.
  #[serde(rename = "shoes")]
  shoes: Option<Vec<::models::SummaryGear>>
}

impl DetailedAthlete {
  pub fn new() -> DetailedAthlete {
    DetailedAthlete {
      id: None,
      resource_state: None,
      firstname: None,
      lastname: None,
      profile_medium: None,
      profile: None,
      city: None,
      state: None,
      country: None,
      sex: None,
      premium: None,
      summit: None,
      created_at: None,
      updated_at: None,
      follower_count: None,
      friend_count: None,
      measurement_preference: None,
      ftp: None,
      weight: None,
      clubs: None,
      bikes: None,
      shoes: None
    }
  }

  pub fn set_id(&mut self, id: i32) {
    self.id = Some(id);
  }

  pub fn with_id(mut self, id: i32) -> DetailedAthlete {
    self.id = Some(id);
    self
  }

  pub fn id(&self) -> Option<&i32> {
    self.id.as_ref()
  }

  pub fn reset_id(&mut self) {
    self.id = None;
  }

  pub fn set_resource_state(&mut self, resource_state: i32) {
    self.resource_state = Some(resource_state);
  }

  pub fn with_resource_state(mut self, resource_state: i32) -> DetailedAthlete {
    self.resource_state = Some(resource_state);
    self
  }

  pub fn resource_state(&self) -> Option<&i32> {
    self.resource_state.as_ref()
  }

  pub fn reset_resource_state(&mut self) {
    self.resource_state = None;
  }

  pub fn set_firstname(&mut self, firstname: String) {
    self.firstname = Some(firstname);
  }

  pub fn with_firstname(mut self, firstname: String) -> DetailedAthlete {
    self.firstname = Some(firstname);
    self
  }

  pub fn firstname(&self) -> Option<&String> {
    self.firstname.as_ref()
  }

  pub fn reset_firstname(&mut self) {
    self.firstname = None;
  }

  pub fn set_lastname(&mut self, lastname: String) {
    self.lastname = Some(lastname);
  }

  pub fn with_lastname(mut self, lastname: String) -> DetailedAthlete {
    self.lastname = Some(lastname);
    self
  }

  pub fn lastname(&self) -> Option<&String> {
    self.lastname.as_ref()
  }

  pub fn reset_lastname(&mut self) {
    self.lastname = None;
  }

  pub fn set_profile_medium(&mut self, profile_medium: String) {
    self.profile_medium = Some(profile_medium);
  }

  pub fn with_profile_medium(mut self, profile_medium: String) -> DetailedAthlete {
    self.profile_medium = Some(profile_medium);
    self
  }

  pub fn profile_medium(&self) -> Option<&String> {
    self.profile_medium.as_ref()
  }

  pub fn reset_profile_medium(&mut self) {
    self.profile_medium = None;
  }

  pub fn set_profile(&mut self, profile: String) {
    self.profile = Some(profile);
  }

  pub fn with_profile(mut self, profile: String) -> DetailedAthlete {
    self.profile = Some(profile);
    self
  }

  pub fn profile(&self) -> Option<&String> {
    self.profile.as_ref()
  }

  pub fn reset_profile(&mut self) {
    self.profile = None;
  }

  pub fn set_city(&mut self, city: String) {
    self.city = Some(city);
  }

  pub fn with_city(mut self, city: String) -> DetailedAthlete {
    self.city = Some(city);
    self
  }

  pub fn city(&self) -> Option<&String> {
    self.city.as_ref()
  }

  pub fn reset_city(&mut self) {
    self.city = None;
  }

  pub fn set_state(&mut self, state: String) {
    self.state = Some(state);
  }

  pub fn with_state(mut self, state: String) -> DetailedAthlete {
    self.state = Some(state);
    self
  }

  pub fn state(&self) -> Option<&String> {
    self.state.as_ref()
  }

  pub fn reset_state(&mut self) {
    self.state = None;
  }

  pub fn set_country(&mut self, country: String) {
    self.country = Some(country);
  }

  pub fn with_country(mut self, country: String) -> DetailedAthlete {
    self.country = Some(country);
    self
  }

  pub fn country(&self) -> Option<&String> {
    self.country.as_ref()
  }

  pub fn reset_country(&mut self) {
    self.country = None;
  }

  pub fn set_sex(&mut self, sex: String) {
    self.sex = Some(sex);
  }

  pub fn with_sex(mut self, sex: String) -> DetailedAthlete {
    self.sex = Some(sex);
    self
  }

  pub fn sex(&self) -> Option<&String> {
    self.sex.as_ref()
  }

  pub fn reset_sex(&mut self) {
    self.sex = None;
  }

  pub fn set_premium(&mut self, premium: bool) {
    self.premium = Some(premium);
  }

  pub fn with_premium(mut self, premium: bool) -> DetailedAthlete {
    self.premium = Some(premium);
    self
  }

  pub fn premium(&self) -> Option<&bool> {
    self.premium.as_ref()
  }

  pub fn reset_premium(&mut self) {
    self.premium = None;
  }

  pub fn set_summit(&mut self, summit: bool) {
    self.summit = Some(summit);
  }

  pub fn with_summit(mut self, summit: bool) -> DetailedAthlete {
    self.summit = Some(summit);
    self
  }

  pub fn summit(&self) -> Option<&bool> {
    self.summit.as_ref()
  }

  pub fn reset_summit(&mut self) {
    self.summit = None;
  }

  pub fn set_created_at(&mut self, created_at: String) {
    self.created_at = Some(created_at);
  }

  pub fn with_created_at(mut self, created_at: String) -> DetailedAthlete {
    self.created_at = Some(created_at);
    self
  }

  pub fn created_at(&self) -> Option<&String> {
    self.created_at.as_ref()
  }

  pub fn reset_created_at(&mut self) {
    self.created_at = None;
  }

  pub fn set_updated_at(&mut self, updated_at: String) {
    self.updated_at = Some(updated_at);
  }

  pub fn with_updated_at(mut self, updated_at: String) -> DetailedAthlete {
    self.updated_at = Some(updated_at);
    self
  }

  pub fn updated_at(&self) -> Option<&String> {
    self.updated_at.as_ref()
  }

  pub fn reset_updated_at(&mut self) {
    self.updated_at = None;
  }

  pub fn set_follower_count(&mut self, follower_count: i32) {
    self.follower_count = Some(follower_count);
  }

  pub fn with_follower_count(mut self, follower_count: i32) -> DetailedAthlete {
    self.follower_count = Some(follower_count);
    self
  }

  pub fn follower_count(&self) -> Option<&i32> {
    self.follower_count.as_ref()
  }

  pub fn reset_follower_count(&mut self) {
    self.follower_count = None;
  }

  pub fn set_friend_count(&mut self, friend_count: i32) {
    self.friend_count = Some(friend_count);
  }

  pub fn with_friend_count(mut self, friend_count: i32) -> DetailedAthlete {
    self.friend_count = Some(friend_count);
    self
  }

  pub fn friend_count(&self) -> Option<&i32> {
    self.friend_count.as_ref()
  }

  pub fn reset_friend_count(&mut self) {
    self.friend_count = None;
  }

  pub fn set_measurement_preference(&mut self, measurement_preference: String) {
    self.measurement_preference = Some(measurement_preference);
  }

  pub fn with_measurement_preference(mut self, measurement_preference: String) -> DetailedAthlete {
    self.measurement_preference = Some(measurement_preference);
    self
  }

  pub fn measurement_preference(&self) -> Option<&String> {
    self.measurement_preference.as_ref()
  }

  pub fn reset_measurement_preference(&mut self) {
    self.measurement_preference = None;
  }

  pub fn set_ftp(&mut self, ftp: i32) {
    self.ftp = Some(ftp);
  }

  pub fn with_ftp(mut self, ftp: i32) -> DetailedAthlete {
    self.ftp = Some(ftp);
    self
  }

  pub fn ftp(&self) -> Option<&i32> {
    self.ftp.as_ref()
  }

  pub fn reset_ftp(&mut self) {
    self.ftp = None;
  }

  pub fn set_weight(&mut self, weight: f32) {
    self.weight = Some(weight);
  }

  pub fn with_weight(mut self, weight: f32) -> DetailedAthlete {
    self.weight = Some(weight);
    self
  }

  pub fn weight(&self) -> Option<&f32> {
    self.weight.as_ref()
  }

  pub fn reset_weight(&mut self) {
    self.weight = None;
  }

  pub fn set_clubs(&mut self, clubs: Vec<::models::SummaryClub>) {
    self.clubs = Some(clubs);
  }

  pub fn with_clubs(mut self, clubs: Vec<::models::SummaryClub>) -> DetailedAthlete {
    self.clubs = Some(clubs);
    self
  }

  pub fn clubs(&self) -> Option<&Vec<::models::SummaryClub>> {
    self.clubs.as_ref()
  }

  pub fn reset_clubs(&mut self) {
    self.clubs = None;
  }

  pub fn set_bikes(&mut self, bikes: Vec<::models::SummaryGear>) {
    self.bikes = Some(bikes);
  }

  pub fn with_bikes(mut self, bikes: Vec<::models::SummaryGear>) -> DetailedAthlete {
    self.bikes = Some(bikes);
    self
  }

  pub fn bikes(&self) -> Option<&Vec<::models::SummaryGear>> {
    self.bikes.as_ref()
  }

  pub fn reset_bikes(&mut self) {
    self.bikes = None;
  }

  pub fn set_shoes(&mut self, shoes: Vec<::models::SummaryGear>) {
    self.shoes = Some(shoes);
  }

  pub fn with_shoes(mut self, shoes: Vec<::models::SummaryGear>) -> DetailedAthlete {
    self.shoes = Some(shoes);
    self
  }

  pub fn shoes(&self) -> Option<&Vec<::models::SummaryGear>> {
    self.shoes.as_ref()
  }

  pub fn reset_shoes(&mut self) {
    self.shoes = None;
  }

}



